-- create schema modcaketwo_db;

use modcaketwo_db;

CREATE TABLE posts(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(256),
	body TEXT,
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL	
);


INSERT INTO posts(title, body, created)
	VALUES("TITLE FIRST POST BLOG","CONTENT FIRST POST BLOG CAKEPHP 2.X",NOW());

INSERT INTO posts(title, body, created)
	VALUES("TITLE SECOND  POST BLOG","CONTENT SECOND POST BLOG CAKEPHP 2.X",NOW());

INSERT INTO posts(title, body, created)
	VALUES("TITLE THIRD POST BLOG","CONTENT THIRD POST BLOG CAKEPHP 2.X",NOW());

CREATE TABLE authors(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	name varchar(45),
	email varchar(120),
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL
);
